- test/integration/sagemaker/test_mnist.py
Update container integration tests to use npy format as default for prediction.
> Use npy format as default for prediction.

- src/sagemaker_pytorch_container/serving.py
- test/integration/__init__.py
- test/integration/local/test_serving.py
- test/resources/call_model_fn_once.py
- test/unit/test_serving.py
https://github.com/awslabs/amazon-sagemaker-examples/issues/341
- change serving.py so user_module initialization only happens once, instead of on each request.
> initialize model once

- test/integration/sagemaker/conftest.py
Use instance_type instead of the tag to determine whether the test needs to be skipped.
> Use instance_type instead of the tag

- setup.py
There was a breaking change in [SageMaker Containers 2.2.0](https://github.com/aws/sagemaker-containers/blob/master/CHANGELOG.rst#220), which #57 took into account.
> bump minimum sagemaker-containers version to 2.2.0

- docker/1.0.0/base/Dockerfile.cpu
- docker/1.0.0/base/Dockerfile.gpu
- setup.py
pip 19.0 gets released today and there's error during base image build using pip 19.0. The error is:
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 176, in main 
status = self.run(options, args) 
File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 346, in run 
session=session, autobuilding=True 
File "/usr/local/lib/python2.7/dist-packages/pip/_internal/wheel.py", line 848, in build 
assert building_is_possible 
AssertionError 
Although there seems workaround for this, it's hard to tell whether it's good or not since release notes are not available for pip 19.0 now. So the best way for now is to freeze pip to <=18.1.
By submitting …
> freeze pip version to <=18.1

- docker/1.0.0/base/Dockerfile.cpu
- docker/1.0.0/base/Dockerfile.gpu
https://github.com/aws/sagemaker-containers/issues/159
Add PYTHONIOENCODING=UTF-8 for python 2 container to encode with utf-8 as default.
Reference:
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING
> Fix unicode display problem in py2 container

- docker/1.0.0/base/Dockerfile.cpu
- docker/1.0.0/base/Dockerfile.gpu
- setup.py
the current 1.0.0 container shipped with torchvision 0.2.1
there is a newever release 0.2.2 which is not fully backwards compatible
at least in the way the datasets are stored. This could impact
customers who suddenly receive a new version of a dependency w/o any
control over it.
> Freeze TorchVision to 0.2.1

- setup.py
Fix for the following exception:
> ContextualVersionConflict: (PyYAML 5.1 (/usr/lib64/python2.7/dist-packages), Requirement.parse('PyYAML<4,>=3.10'), set(['docker-compose']))
> Freeze PyYAML version to avoid conflict with Docker Compose

- test/conftest.py
- test/integration/local/test_single_machine_training.py
- test/utils/local_mode_utils.py
Part 2 of some number for using the Python SDK in our integ tests (see #86).
> Use the SageMaker Python SDK for local integ single-machine training tests

- setup.py
- test/integration/local/test_distributed_training.py
- test/integration/local/test_single_machine_training.py
With https://github.com/aws/sagemaker-python-sdk/pull/746, Local Mode exports training artifacts even after job failure, so we can now test for the existence of a failure file.
Also updated the role following #91 and https://github.com/aws/sagemaker-chainer-container/pull/77
> Use dummy role in tests and update local failure integ test

- setup.py
That version of SageMaker Containers had a fix to honor the `SAGEMAKER_MODEL_SERVER_TIMEOUT` setting.
> Bump minimum SageMaker Containers version to 2.4.6 and pin SageMaker Python SDK to 1.18.16

- buildspec.yml
Fix broken line of buildspec. Current error is:
Command did not exit successfully GPU_TAG="$FRAMEWORK_VERSION-gpu-py$GPU_PY_VERSION-$build_id" \ docker build -f "$build_dir/$gpu_dockerfile" --build-arg py_version=$GPU_PY_VERSION -t $PREPROD_IMAGE:$GPU_TAG . exit status 127 
> fix broken line of buildspec

- test/conftest.py
- test/integration/sagemaker/test_distributed_operations.py
- test/integration/sagemaker/test_mnist.py
Disable the test_mnist_gpu py2 test for now because it never passed. We will have a separate task to have it fixed after PyTorch 1.1 upgrade.
Also I didn't write a conftest function but followed the convention that other test in this file that skips because of python version. And we will remove the skip condition after we fix the issue.
> fix: disable test_mnist_gpu for py2 for now

- buildspec-release.yml
- test/conftest.py
Add placeholder in test commands for cpu-instance-type and aws-id
Make regional release tests work in the new regions.
> Update no-p2 and no-p3 regions.

- docker/1.2.0/py2/Dockerfile.cpu
- docker/1.2.0/py2/Dockerfile.gpu
- docker/1.2.0/py3/Dockerfile.cpu
- docker/1.2.0/py3/Dockerfile.gpu
Running the container like:
```
docker run -it <image_id> 
```
causes immediate exit unless supplied with a command such as /bin/bash as an argument. If provided as an argument, the bash script start_with_right_hostname.sh correctly evals it. 
Adding /bin/bash as default CMD to start when container is started in interactive/daemon mode.
> Add /bin/bash as default CMD

- docker/1.2.0/py2/Dockerfile.gpu
- docker/1.2.0/py3/Dockerfile.gpu
Changing pip prebuilt wheel to use official pip wheel for torchvision
> Installing tochvision from official pip wheel

- docker/1.2.0/py2/Dockerfile.gpu
- docker/1.2.0/py3/Dockerfile.gpu
Removing extra packages to optimize space in GPU containers 
> Removing extra packages to optimize space

- buildspec.yml
related:
* https://github.com/aws/sagemaker-mxnet-serving-container/pull/76
* https://github.com/aws/sagemaker-mxnet-container/pull/113
* https://github.com/aws/sagemaker-chainer-container/pull/107
> change: use regional endpoint for STS in builds

- buildspec.yml
Right now only Python 2 is being tested with the local GPU tests
> change: run local GPU tests for Python 3

- docker/1.4.0/py2/Dockerfile.gpu
Jupiter_client version 6.0.0 does not support python2.
https://tod.amazon.com/test_runs/53ba792d-6fb2-4192-9cab-f7eb5be8c880
Install jupyter_client 5.3.4 in advance for py2 gpu image
> Install jupyter_client 5.3.4 in advance for py2 gpu image

- setup.py
sagemaker-containers==2.8.2 contains aws/sagemaker-containers#261, which has a fix for requirements.txt support.
> fix: upgrade sagemaker-containers to 2.8.2

- setup.py
- test-toolkit/integration/sagemaker/test_mnist.py
- test/integration/sagemaker/test_mnist.py
- Consume changes from https://github.com/aws/sagemaker-containers/pull/268
- Update test to train with more than 1 epoch
> Upgrade sagemaker-containers and test with more than 1 epoch

- test-toolkit/resources/mnist/mnist.py
- test/resources/mnist/mnist.py
Noticed that the training scripts still had inference code (leftover from before the images split)
> infra: remove (unused) model_fn from training scripts

- buildspec-toolkit.yml
- buildspec.yml
- test-toolkit/integration/sagemaker/test_distributed_operations.py
- test-toolkit/integration/sagemaker/test_mnist.py
- test/integration/sagemaker/test_distributed_operations.py
- test/integration/sagemaker/test_mnist.py
- test/integration/sagemaker/test_training_smdebug.py
This is to speed up the PR builds. I set `n` to the number of tests, as determined by `pytest --collect-only`.
It seems to have helped with the overall times:
* the toolkit one normally takes 2-2.5 hours; this time it took just under an hour
* the other one normally takes 4 hours; this time it took a little over 2 hours
> infra: parallelize SageMaker integ test runs

- src/sagemaker_pytorch_container/training.py
- test/unit/test_train.py
With the latest heterogeneous cluster changes, the master node is not always algo-1. 
Derive master node from the training env rather than relying on the first node of the hosts.
> fix: deriver master node from training environment

- src/sagemaker_pytorch_container/training.py
- test/unit/test_train.py
* Allow customers to launch native PTDDP jobs with `nccl` backend using a new distribution value: `{ "pytorchddp": "enabled": "true",  <other options> }}`
* Uses smdataparallel runner for launch, same as smdistributed backend.
* Connected PRs: https://github.com/aws/sagemaker-python-sdk/pull/3223
> feature: add support for native PT DDP distribution

- CONTRIBUTING.md
- README.rst
> documentation: update README and contributing guidelines

- setup.py
- src/sagemaker_pytorch_container/training.py
- test/unit/test_train.py
Add support for `torch_distributed` for Trainium instance types
- PySDK PR: https://github.com/aws/sagemaker-python-sdk/pull/3424
- SM Toolkit PR: https://github.com/aws/sagemaker-training-toolkit/pull/154
- Updated `sagemaker-training` requirement to `>=4.3.0` for `torch_distributed` support. 
> feature: Add torch_distributed support for Trainium

- src/sagemaker_pytorch_container/training.py
- test/unit/test_train.py
*Description of changes:* feature: add PyTorch version environment variable, to facilitate SMTT
Please refer to SMTT PR: https://github.com/aws/sagemaker-training-toolkit/pull/182
> Add PyTorch version environment variable, to facilitate SMTT

- setup.py
Latest coverage version will go with a `No data to report.` error.
Reverting coverage to 6.5.0 for unblocking the pipeline.
> Fix: pin coverage version to fix pipeline issue

- src/sagemaker_pytorch_container/training.py
- test/unit/test_train.py
For the use-cases of Studio Local Mode, we need to bypass the DNS check for enabling single/multi-container run.
> change: bypass DNS check for studio local exec
