aws/sagemaker-pytorch-training-toolkit

docker/0.4.0/final/Dockerfile.cpu, docker/0.4.0/final/Dockerfile.gpu, setup.py, src/sagemaker_pytorch_container/serving.py, src/sagemaker_pytorch_container/training.py, test/unit/test_serving.py, test/unit/test_train.py
aws/sagemaker-containers#95
Tests will fail until new sagemaker containers is in pypi.
=> Allow local code directories for training and serving

docker/0.4.0/final/Dockerfile.cpu, docker/0.4.0/final/Dockerfile.gpu
Remove unnecessary instalation of sagemaker-container library in docker file since pytorch-container already depends on a specific version of it in setup.py
=> Remove unnecessary instalation of sagemaker-container in docker file

docker/1.0.0/base/Dockerfile.gpu
=> Switch to use cuda 9.2

docker/1.0.0/base/Dockerfile.cpu, docker/1.0.0/base/Dockerfile.gpu, test/conftest.py, test/resources/distributed_operations.py, test/resources/mnist/mnist.py
=> Update dockerfile and tests to use 1.0.0

setup.py, test/conftest.py, test/integration/local/test_distributed_training.py, test/integration/local/test_serving.py, test/integration/sagemaker/conftest.py, test/resources/mnist/mnist.py, test/utils/local_mode.py
local gpu tests need to pass runtime=nvidia for nvidia-docker2
=> FIx local GPU tests with nvidia-docker2

setup.py, test/unit/test_serving.py
=> Allow for a range of versions for sagemaker containers

setup.py, test/integration/local/test_distributed_training.py, test/resources/call_model_fn_once.py, test/unit/test_train.py, test/utils/local_mode.py, tox.ini
- update sagemaker-containers to 2.2.3
- fix test and flake8 errors
=> update sagemaker-containers to 2.2.3

test/resources/mnist/mnist.py
Our builds are failing due to tests not passing. After following the stack trace to [this code](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L1567-L1569), this change seemed like the easiest way to get the tests to pass. Tested locally on my laptop.
=> Pass None instead of False when calculating loss in test script

setup.py, test/unit/test_serving.py
=> bump and unpin SageMaker Containers version

setup.py
=> bump min SageMaker Containers version to 2.3.5

src/sagemaker_pytorch_container/serving.py, test/unit/test_serving.py
fix response content_type handling:
- no accept header
- mimetype and content_type handled correctly
=> fix response content_type handling

test/integration/sagemaker/test_distributed_operations.py
see https://github.com/aws/sagemaker-tensorflow-container/pull/169
=> Specify region when creating S3 resource in integ tests

setup.py
=> Unfreeze numpy version.

docker/1.0.0/base/Dockerfile.cpu, docker/1.0.0/base/Dockerfile.gpu, setup.py
=> Add opencv support.

docker/1.0.0/base/Dockerfile.cpu, docker/1.0.0/base/Dockerfile.gpu, test/resources/mnist/mnist.py
Add missing rendering dependencies for opencv and a simple test.
=> Add missing rendering dependencies for opencv and a simple test.

test/integration/local/test_distributed_training.py, test/integration/sagemaker/test_distributed_operations.py
=> Use the SageMaker Python SDK for local integ distributed training tests

test/integration/sagemaker/test_distributed_operations.py
This test takes too long without output, adding a default timeout.
=> Add timeout to test_mnist_gpu test.

README.rst
=> fix broken link in README

buildspec.yml
Add pull request buildspec. This buildspec will be used by AWS CodeBuild.
=> Add AWS CodeBuild buildspec for pull request

test/conftest.py
Skip tests in GPU instance restricted regions.
=> skip tests in gpu instance restricted regions

test/integration/sagemaker/test_mnist.py
=> fix: unmark 2 deploy tests

setup.py
To include a change from sagemaker-containers
=> fix: upgrade sagemaker-container version

buildspec.yml, docker/1.2.0/py2/Dockerfile.cpu, docker/1.2.0/py2/Dockerfile.gpu, docker/1.2.0/py3/Dockerfile.cpu, docker/1.2.0/py3/Dockerfile.gpu, lib/start_with_right_hostname.sh, setup.py, test/integration/__init__.py, test/integration/local/test_single_machine_training.py
Pytorch 1.2.0 py2 and py3 dockerfiles added 
Included horovod in gpu files.
=> Pytorch 1.2 py2 py3 dockerfiles added

test/conftest.py
=> change: update instance type region availability.

src/sagemaker_pytorch_container/training.py, test/unit/test_train.py
https://github.com/aws/sagemaker-python-sdk/pull/941
same thing as https://github.com/aws/sagemaker-mxnet-container/pull/114
=> change: use SageMaker Containers' ProcessRunner for executing the entry point

setup.py
GitHub notified us that there was an issue discovered in older versions of Pillow, which could cause the library to either allocate very large amounts of memory or take an extremely long period of time to process the image.
=> change: upgrade pillow to 6.2.0

setup.py
https://github.com/aws/sagemaker-python-sdk/issues/1100
incorporating https://github.com/aws/sagemaker-containers/pull/233
=> change: upgrade sagemaker-containers to 2.5.11

setup.py, src/sagemaker_pytorch_container/__init__.py, src/sagemaker_pytorch_container/deep_learning_container.py, src/sagemaker_pytorch_container/training.py, test/__init__.py, test/conftest.py, test/integration/__init__.py, test/integration/local/__init__.py, test/integration/local/test_distributed_training.py, test/integration/local/test_single_machine_training.py, test/integration/sagemaker/__init__.py, test/integration/sagemaker/test_dgl.py, test/integration/sagemaker/test_distributed_operations.py, test/integration/sagemaker/test_mnist.py, test/integration/sagemaker/test_training_smdebug.py, test/integration/sagemaker/timeout.py, test/resources/call_model_fn_once.py, test/resources/distributed_operations.py, test/resources/fastai/cifar/cifar.py, test/resources/fastai/mnist.py, test/resources/mnist/mnist.py, test/resources/mnist/mnist_1d.py, test/resources/mnist/smdebug_mnist.py, test/unit/test_deep_learning_containers.py, test/unit/test_train.py, test/utils/__init__.py, test/utils/image_utils.py, test/utils/local_mode_utils.py
=> change: update copyright year in license header

docker/1.3.1/py2/Dockerfile.cpu, docker/1.3.1/py2/Dockerfile.gpu, docker/1.3.1/py3/Dockerfile.cpu, docker/1.3.1/py3/Dockerfile.gpu, setup.py
* Bump awscli version to 1.17.7
* Constrain spyder to <4.0 when installed by conda
=> update: Bump awscli version and constrain spyder on conda

MANIFEST.in, buildspec-deploy.yml, buildspec-release.yml, buildspec.yml, docker/1.3.1/py2/Dockerfile.cpu, docker/1.3.1/py2/Dockerfile.gpu, docker/1.3.1/py3/Dockerfile.cpu, docker/1.3.1/py3/Dockerfile.gpu, setup.py
*Description of changes:* Add release to PyPI. Change package name to sagemaker-pytorch-training.
=> feature: Add release to PyPI. Change package name to sagemaker-pytorch-training.

tox.ini
=> Add twine section to tox.

.flake8, buildspec.yml, test/conftest.py, tox.ini
*Description of changes:* Fix flake8 erros. Add flake configuration to run during PR.
=> change: Fix flake8 erros. Add flake configuration to run during PR.

docker/1.4.0/py2/Dockerfile.cpu, docker/1.4.0/py2/Dockerfile.gpu, docker/1.4.0/py3/Dockerfile.cpu, docker/1.4.0/py3/Dockerfile.gpu
Update license URL for PyTorch
=> update: Update license URL

setup.py
feature: Remove unnecessary dependencies.
=> feature: Remove unnecessary dependencies.

tox.ini
change: Fix python 2 tox dependencies.
=> change: Fix python 2 tox dependencies.

docker/1.4.0/py3/Dockerfile.cpu, docker/1.4.0/py3/Dockerfile.gpu, setup.py, test/integration/sagemaker/test_experiments.py
upgrade to latest sagemaker-experiments
=> upgrade to latest sagemaker-experiments

setup.py, test/integration/sagemaker/test_experiments.py
install sagemaker-experiments package only for 3.6
=> install sagemaker-experiments package only for 3.6

setup.py
install sm experiments always when python 3.6 or greater
=> install sm experiments always when python 3.6 or greater

buildspec-release.yml
The unit tests were moved from `test/` to `test-toolkit/`.
=> infra: run test-toolkit unit tests for release

docker/1.4.0/py2/Dockerfile.cpu, docker/1.4.0/py2/Dockerfile.gpu, docker/1.4.0/py3/Dockerfile.cpu, docker/1.4.0/py3/Dockerfile.gpu
=> upgrade pillow etc. to fix safety issues in 1.4.0 dockerfiles

test-toolkit/integration/__init__.py, test-toolkit/integration/local/test_requirements.py, test-toolkit/resources/requirements/entry.py, test-toolkit/resources/requirements/requirements.txt
https://github.com/aws/sagemaker-python-sdk/issues/1371
follow-up to #187 
=> infra: add requirements.txt integ test

docker/1.4.0/py2/Dockerfile.cpu, docker/1.4.0/py2/Dockerfile.gpu, docker/1.4.0/py3/Dockerfile.cpu, docker/1.4.0/py3/Dockerfile.gpu
This copies the changes made in https://github.com/aws/sagemaker-pytorch-serving-container/pull/66
=> fix: change miniconda installation in 1.4.0 Dockerfiles

buildspec.yml, setup.py, test/integration/sagemaker/test_distributed_operations.py, test/integration/sagemaker/test_mnist.py, tox.ini
=> infra: do not duplicate test dependencies in tox.ini

setup.py
=> change: Pin SageMaker version to less than v2

buildspec-gputests.yml, buildspec-unittests.yml
* Added GPU integration test buildspec
* Added unit test buildspec
=> change: Add GPU and unit test buildspecs

src/sagemaker_pytorch_container/training.py
* Fix docstring style in `training.py`
=> docs: Fix docstring style in training.py

buildspec-gputests.yml, buildspec.yml
* Removed GPU and unit tests from `buildspec.yml`
=> change: Update main buildspec to only perform CPU integration tests

src/sagemaker_pytorch_container/training.py, test/container/1.10.2/Dockerfile.dlc.trcomp, test/unit/test_train.py
1. Support new runner for distributed training with PT-XLA
=> Feature: Support new distribution mechanism for PT-XLA
